apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newName: han2000w/sample
- name: han2000w/sample
  newTag: v37
resources:
- guestbook-ui-deployment.yaml
